version: '3'
volumes:
  vscode_server:
services:
  server:
    build: .
    container_name: system-design-primer
    env_file:
      - .env
      - .env.local
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/app
      - vscode_server:/root/.vscode-server
    working_dir: /app
    command: ./docker-compose.server.command
