version: '3'
volumes:
  vscode_server:
services:
  server:
    build:
      context: .
      args:
        - TIMEZONE=${TIMEZONE}
    container_name: system-design-primer
    env_file:
      - .env
      - .env.local
    ports:
      - "${SERVER_PORT}:4000"
      - "${LIVERELOAD_PORT}:35729"
    volumes:
      - .:/app
      - ${SSH_DIR:-~/.ssh}:/root/.ssh
      - vscode_server:/root/.vscode-server
    working_dir: /app
    command: ./docker-compose.server.command
