#!/usr/bin/env bash
# Run other scripts in the ./scripts directory
set -e

# Load environment variables from .env files
set -o allexport
source .env
[ -f .env.local ] && source .env.local
set +o allexport

# Run the target script
target_script="$1" # first argument is the target script's name
shift # already used the first argument, so shift it off
"./scripts/$target_script" "$@" # run with the remaining arguments
