#!/usr/bin/env bash
# Build the site for deployment to GitHub Pages
set -euo pipefail

# Build the site into "./docs" (the GitHub Pages directory)
docker compose \
    exec -it -e JEKYLL_ENV=production server \
    bundle exec jekyll build -d ./docs

# Generate broken links report
./scripts/brokenlinks
