#!/usr/bin/env bash
cat <<EOF
Available commands:
========================
attach      : Attach to the development container
build       : Build the app image
build-site  : Build the site to deploy to GitHub Pages
down        : Stop and remove what was created by up
help        : Show this help message
serve       : Serve the site locally
up          : Start the development containers
EOF

