#!/usr/bin/env bash
# Serve the site locally
docker exec -it system-design-primer \
    bundle exec jekyll serve \
        --baseurl="" \
        --force_polling \
        --host 0.0.0.0 \
        --port 4000 \
        --livereload