#!/usr/bin/env bash
# Start the Jekyll server in the container to serve the site locally
docker compose exec -it server \
    bundle exec jekyll serve \
        --baseurl="" \
        --force_polling \
        --host 0.0.0.0 \
        --port ${SERVER_PORT:?missing} \
        --incremental \
        --livereload
