#!/usr/bin/env bash
# Run other scripts in the "./scripts" directory
set -e

# Call "help" if no arguments are provided
if [ $# -eq 0 ]; then
    ./scripts/help "$@"
    exit 0
fi

# First argument is the script to run, the rest are arguments to the script
target_script="./scripts/$1"
if [ ! -f "$target_script" ]; then
    # If no matching script found, pass through to "docker compose"
    docker compose "$@"
else
    # If the script exists, run it with the remaining arguments
    shift
    "$target_script" "$@"
fi
